### ISSUE TITLE
how do i get rid of the blue focus rectangle ?

### ISSUE THREAD

**Issue by bakman2** [kenwheeler/slick#1546]
as subject how do i get rid of the blue focus rectangle ?
I don't see it in the styles ?

**Comment by simeydotme** [comment]
```css
.slick-slide:focus { outline: none; }
```
@msrafi @kenwheeler ... much discussion about this outline.
#1544 #1537
https://github.com/kenwheeler/slick/pull/1467#issuecomment-120635431
