### ISSUE TITLE
Contents will be gone when a container element is hidden at start

### ISSUE THREAD

**Issue by Timberland-7** [kenwheeler/slick#1573]
When a wrapper element is set to be hidden at start, all imgs\contents in the slick wrapper are gone ( width is set to 0 ) untill you click one of the narrows

https://jsfiddle.net/ap283puf/8/

But if you remove the hidden class ( in the demostration ) and then try to hide and show the wrapper it's all good

**Comment by gausarts** [comment]
Try using class 'element-invisible':
https://jsfiddle.net/ap283puf/9/

It is not hiding which removes image information, but clipping while preserving dimensions so Slick still has a chance to read it.

**Comment by danwerner** [comment]
I was able to solve a similar problem (slick wouldn't calculate the slides' width/height correctly when the slider was hidden at the time `slick()` is called) using the following CSS:

```css
.element-invisible {
  position: absolute !important;
  top: -9999px !important;
  left: -9999px !important;
}
```

I still had to set the element's width to the parent container's width via JavaScript right *before* the .element-invisible class is removed.
