### ISSUE TITLE
Display one item and half of the prev/next ones

### ISSUE THREAD

**Issue by lbineau** [kenwheeler/slick#1784]
Hi,

http://jsfiddle.net/lbineau/vdnphxpg/

I would like to create this effect but I can't find any example :
![slick](https://cloud.githubusercontent.com/assets/1534688/10192466/daeff862-677c-11e5-9cb2-87027b2d5fce.jpg)
I tried to do it with transform but at some point there are problems with cloned items (and absolutly not with dragging).

```javascript
$('.slick').slick({
  centerMode: true,
  centerPadding: '0',
  slidesToShow: 3
});
```
```scss
.slick-slide{
  outline: 0;
  width: 168px;
  height: 309px;
  transition: transform 0.5s;
  &.slick-current.slick-active{
    transform: none;
  }
  &.slick-active{
    transform: translateX(-50%);
  }
  &.slick-current + .slick-active{
    transform: translateX(50%);
  }
}
```

Any idea ?
