### ISSUE TITLE
Prev and Next arrows appear on top and bottom respectively

### ISSUE THREAD

**Issue by GonzaloCalandria** [kenwheeler/slick#1811]
Why the arrows prev and next appears on the top and the bottom of the carousel?
I need that they appear on the sides but i haven't any luck with that.

I'm using the JS code like this:

```javascript
$('#slick-carousel').slick({
        infinite: true,
        autoplay: true,
        arrows: true,
        centerMode: false,
        mobileFirst: false,
        variableWidth: false,
        prevArrow: '<div><button type="button" class="tc-twitter-arrows tc-arrow-prev"></button></div>',
        nextArrow: '<div><button type="button" class="tc-twitter-arrows tc-arrow-next"></button></div>',
        dots: false,
        responsive: [
        {
          breakpoint: 768,
          settings: {
            arrows: false,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 2
          }
        },
        {
          breakpoint: 480,
          settings: {
            arrows: false,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 1
          }
        }
      ]
    });
```
This is the CSS for the buttons:
```css
.tc-twitter-arrows
{
    background-image: url('http://welovestyles.com/wp-content/uploads/loook/carousel-arrows-333333-50.png');
    background-repeat: no-repeat;
    background-color: transparent;
    border: none;
    margin: 0;
}

.tc-twitter-arrows.tc-arrow-prev{
    width: 40px;
    height: 40px;
    background-position: 0 0;
}
.tc-twitter-arrows.tc-arrow-next{
    width: 40px;
    height: 40px;
    background-position: -40 0;
}
```

Also, i have a question about the basic "must" css styles that need to have the slides and the container (i'm having issues with the widths and heights).

Kind regards,
Gonzalo.
