### ISSUE TITLE
CenterMode / Responsive

### ISSUE THREAD

**Issue by JordanSayner** [kenwheeler/slick#1857]
Hi,

I'm having trouble making my slides resize to fit the browser. I have set up a little test case here - http://jsfiddle.net/omgd1vn1/ 

Basically when the window / viewport is lower than 1000px, i want the slides to reduce in width to match the window width, where as currently, they are staying at 1000px wide and there for the height to change to keep the aspect ratio of the image.

When the window size is below 1000px, i only want to show the active slide, not the slides either side.

All code can be found on JS fiddle. i have also added it below  

```html
<div class="main-gallery">

    <div class="gallery-cell ">
        <a href="#" title="Item 1">
            <img alt="Item 1" src="http://placehold.it/1000x400"> 
            <span class="caption">Item 1</span>
        </a>
    </div>
    <div class="gallery-cell ">
        <a href="#" title="Item 2">
            <img alt="Item 2" src="http://placehold.it/1000x400"> 
            <span class="caption">Item 2</span>
        </a>
    </div>
    <div class="gallery-cell ">
        <a href="#" title="Item 3">
            <img alt="Item 3" src="http://placehold.it/1000x400"> 
            <span class="caption">Item 3</span>
        </a>
    </div>
    <div class="gallery-cell ">
        <a href="#" title="Item ">
            <img alt="Item 4" src="http://placehold.it/1000x400"> 
            <span class="caption">Item 4</span>
        </a>
    </div>
    <div class="gallery-cell ">
        <a href="#" title="Item 5">
            <img alt="Item 5" src="http://placehold.it/1000x400"> 
            <span class="caption">Item 5</span>
        </a>
    </div>
    <div class="gallery-cell ">
        <a href="#" title="Item 6">
            <img alt="Item 6" src="http://placehold.it/1000x400"> 
            <span class="caption">Item 6</span>
        </a>
    </div>

</div>
```

```css
.main-gallery {
    position: relative;
    margin: 0 auto 25px auto;
}
    .gallery-cell {
        opacity: 0.3;
        filter: alpha(opacity=30);
        max-height: 400px;
        max-width: 1000px;
        width: 100%;
        overflow: hidden;
        position: relative;
    }
        .gallery-cell a {
            display: block;
        }
            .gallery-cell a img {
                width: 100%;
                height: 100%;
            }
        .gallery-cell .caption {
            position: absolute;
            bottom: 15px;
            left: 15px;
            padding: 10px;
            opacity: 0;
            filter: alpha(opacity=0);
        }
    .gallery-cell.slick-active {
        opacity: 1;
        filter: alpha(opacity=100);
    }
        .gallery-cell.slick-active .caption {
            opacity: 0.95;
            filter: alpha(opacity=95);
        }

/* SLIDER BUTTONS */
.slick-arrow {
    position: absolute;
	top: 0;
	height: 400px;
	max-width: 1000px;
	width: 200px;
	z-index: 999;
	cursor: pointer;
    background: none;
    border: 0;
    outline: 0;
}

    .slick-next {
        /*right: 50%;
        margin: 0 -1500px 0 0;*/
        right: 0;
    }
    

    .slick-prev {
        /*left: 50%;
        margin: 0 0 0 -1500px;*/
        left: 0;
    }

```

```javascript
$('.main-gallery').slick({
    centerMode: true,
    slidesToShow: 1,
    variableWidth: true,
    adaptiveHeight: true,
    autoplay: true,
    autoplaySpeed: 10000,
});

```
