### ISSUE TITLE
Slide reach enormous dimensions with flexbox ONLY in safari 

### ISSUE THREAD

**Issue by etshi** [kenwheeler/slick#1925]
I found a lot of issues that is related to having the carousel inside a parent with display set to flexbox or table.

But non of the solutions worked for me, My issue is a little bit unique as the carousel works as expected in all browsers even IE except for Safari.

```js
<div id="carousel-movies">
    <div id="carousel-movies-wrapper">
         <img src="http://top-frog.com/stuff/slider/images/slider-test-image-1.gif"/>
         <img src="http://top-frog.com/stuff/slider/images/slider-test-image-2.gif"/>
         <img src="http://top-frog.com/stuff/slider/images/slider-test-image-3.gif"/>
    </div>
</div>
```
```css
#carousel-movies {
    overflow: hidden;
    padding: 0 1rem;
    display: -webkit-box;
    display: -moz-box;
    display: box;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-flow:column wrap;
    -ms-flex-flow:column wrap;
    flex-flow:column wrap;    
    -webkit-box-pack: center;
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
}
#carousel-movies-wrapper {
    -webkit-box-flex: 1;
    -webkit-flex: 0 auto;
    -ms-flex: 0 auto;
    flex: 0 auto;
}
```

Any idea how I could resolve this issue ?
