### ISSUE TITLE
Remove images after they slide out

### ISSUE THREAD

**Issue by keithslater** [kenwheeler/slick#199]
I've noticed that after an image slides out, it is still there but just hidden in some way. Is there a way to remove them so that they aren't there? I am using a magnify plugin on the same slideshow and it shows the images that slid out.

Here's an example. The image in the square on the left slid out of slick but the magnifier still finds it:

![screen shot 2014-04-30 at 4 39 13 pm](https://cloud.githubusercontent.com/assets/940991/2847567/eb8f9ffc-d0af-11e3-82ab-4303ac70b094.png)

**Comment by Cam** [comment]
@keithslater Did you get Slick and Elevate zoom working well together?

**Comment by keithslater** [comment]
No, I ended up using flexslider.

**Comment by Cam** [comment]
Ahh.. kk. Thanks @keithslater. I guess the dream of using an image hover with Slick is still just a dream :p. @kenwheeler anything you could do to make hover zoom on slick-active would be really valuable :)

**Comment by vuongdothanhhuy** [comment]
Hello @keithslater and @Cam 

I just came across the same issue when applying both slick and elevateZoom on my project this morning.

Tried various hacks found on the Internet but still no luck.

After spending almost the evening digging my head into the issue, I finally came up with my own hack:

```LESS
// Here is the trick, written in LESS:
// In real code, this should be scoped further
//  to the slick instance that you want to apply this trick on.

.slick-slide {
  img {
    display: none;
  }
}

.slick-current, .slick-active {
  img {
    display: block;
  }
}
```

The basic idea is to have all slick slides that are inactive to have `display: none;`, so that a mouse hover over it doesn't activate the elevateZoom.

I don't really know why, when applying elevateZoom on slick then we can mouse over out-of-view slides - normally with a slick-only setup this issue doesn't occur.

The current active slick slide will have `display:block;` as normal, and everything works well.

[Here is the demo](https://codepen.io/anon/pen/veeVPR)

I also posted this answer on SO: https://stackoverflow.com/questions/41979734/elevatezoom-with-slick-slider-issues/46548687#46548687

Hope people find it useful somehow. :smiley:
