### ISSUE TITLE
Erroneous styles applied during slide event.

### ISSUE THREAD

**Issue by DrizzlyOwl** [kenwheeler/slick#229]
I've noticed a slight issue when slick reaches the end of a set of images whilst infinite = true. 

As the 1st image slides back into view after the last in the list has been displayed, my table element is forced to 100% width?

My syntax is within a foreach loop and each slide is set up like this.

``` php
<div class="slide clear">
    <table id="slide__img">
        <tr>
        <td>
            <?php if (has_post_thumbnail()) {
                the_post_thumbnail('slider-img');
            } ?>
        </td>
    </tr>
    </table>
    <div class="slide__caption">
        <h2><?php the_title(); ?></h2>
        <p><?php echo wp_trim_words(get_the_excerpt(),40,'...'); ?></p>
        <a href="<?php the_permalink(); ?>" class="btn btn--large btn--block btn--shop-now">Shop Now</a>
    </div>
</div>
```

and the css for this specific area is as follows:

``` scss
.slide{
    display: none;
    height: 500px;
}
.slick-cloned{ display: none; }
    .slick-active{
        display: block;
    }
    #slide__img{
        height: 100%;
        margin: 0;
        padding: 0;
        border: none;
        outline: none;
        background: none;
        width: 70%;
        display: table;
        float: left;
        border-collapse: none;
        tr{
            background: none;
            width: 100%;
        }
        td{
            width: 100%;
            vertical-align:middle;
            text-align: center;
            background: none;
            padding: 0;
            margin: 0;
            img{
                margin: 0 auto;
                display: block;
            }
        }
    }
    .slide__caption{
        width: 30%;
        display: block;
        float: right;
        background: #3A3A3A;
        padding: size(1.5) size(1.5);
        color: white;
        h2{ color: white;}
        p{
            font-size: typesize(0.9);
        }
        height: 500px;
    }
```

Any clues as to why this would happen?
