### ISSUE TITLE
change dots color?

### ISSUE THREAD

**Issue by shanirel** [kenwheeler/slick#245]
Hi Ken,
Awesome plugin. Any chance for dots color setting? 
Tried to change it in the slick-active class with no luck.

**Comment by posi-tiva** [comment]
Hi,
I had the same issue and it didn't work just Setting the color css property like you would for text on the psuedo selector .
Instead I added this 2 rules on the li.slick-active:

background-color: transparent;
overflow: hidden;

**Comment by radiovisual** [comment]
This is what worked for me:

```css
.slick-dots li button:before {
    color: orange;
  }
```
