### ISSUE TITLE
Vertical align slides 

### ISSUE THREAD

**Issue by mweterings** [kenwheeler/slick#281]
Is there a possibility to vertical align the image slides ?

**Comment by floatorhead** [comment]
same problem here. the solution from css-tricks.com doesn't work in my case. maybe due to the images overflowing my actual slider-size. However, I'm a beginner to wedesign and coding...
Could anyone solve the issue so far?

**Comment by tomasguemes** [comment]
Hello,

The technique from css-tricks.com works for me adding a fixed height to the container:

  .slick-track {
    height: 200px;
  }

**Comment by jcoffland** [comment]
@peschee, thanks that worked really well!

**Comment by akazakou** [comment]
peschee, thanks for great solution!

**Comment by danbars** [comment]
That trick is useful to center when the child and parent are unknown.
Since you add explicit height to slick-track, that is no longer the case, and you can center using a simpler techniques, like this one:
```CSS
.slick-track {
height: 200px;
}

.slick-slide {
  top: 50%;
  transform: translateY(-50%);
}
```

That works because top percentage is relative to the parent, while transform percentage is relative to the element itself. So we push it 50% of the parent down, then pull it back up 50% of its own height.

**Comment by casikr** [comment]
Hi, 
using: display: flex; align-items:center on .slick-slide works for me in most browsers.

**Comment by wiesson** [comment]
thanks @peschee - works perfectly! :ok_hand:

**Comment by SarahBaghdadi** [comment]
@peschee's solution only seems to work when I also use @tomasguemes's modification

**Comment by Bondra** [comment]
It's totally hopeless trying to vertical align content within the slider that has an unknown height? I've struggling with this like a maniac. What tha hell am I doing wrong?

**Comment by TarikTz** [comment]
When slider is in vertical mode, image in center is actually last image on start and that bug keeps happening while scrolling. Any idea how to fix this?

**Comment by jpotterm** [comment]
Here's the simplest solution I've found:

```css
.slick-initialized .slick-slide {
    float: none;
    display: inline-block;
    vertical-align: middle;
}
```
