### ISSUE TITLE
Question: Is it possible to include a zero before each dot number if less than 10 ?

### ISSUE THREAD

**Issue by jorgemonte** [kenwheeler/slick#3788]
Hi Everyone,

I am building a simple slider counter using the dots as the element that will manage it.
The idea is simple: I will let the last dot-list element to be the number of slides, and the current one to be the moving counter, with opacity: 1 and visibility: visible only for this item.

The issue is that the designer wants the counter to get the sliders counter like:

01, 02, 03... til 09, so, I need to find a way to include number 0 before each slide-dot, if the number is < 10. 

Is there any way to get it without having to create a separate counter element?
Thank you!

**Comment by ahmadalfy** [comment]
You can actually do that using CSS [like this](http://jsfiddle.net/k6wo3r8v/8/)

```css
.slick-dots li button::before {
  content: "0";
}

.slick-dots li:nth-child(n + 10) button::before {
  content: none;
}
```
