### ISSUE TITLE
slick asNavFor not working properly in rtl mode

### ISSUE THREAD

**Issue by Niloys7** [kenwheeler/slick#3951]
when rtl mode is active the asNavFor is not working properly.
when I click thumbnail item(2) then it's moved it main image item (3) 
check this codepen link below for a live preview.
https://codepen.io/Amirtvs/pen/GRgpyzV

Thanks

**Comment by agustinl** [comment]
Hi @Niloys7 , try with this code:

```html
<div class="container">
        <div class='main' dir="rtl">
          <img src="http://placehold.it/280x170?text=1" alt="">
          <img src="http://placehold.it/280x170?text=2" alt="">
          <img src="http://placehold.it/280x170?text=3" alt="">
          <img src="http://placehold.it/280x170?text=4" alt="">
        </div>
        <div class='nav' dir="rtl">
          <img src="http://placehold.it/280x170?text=1" alt="">
          <img src="http://placehold.it/280x170?text=2" alt="">
          <img src="http://placehold.it/280x170?text=3" alt="">
          <img src="http://placehold.it/280x170?text=4" alt="">
        </div>
</div>
```
**Note the dir="rtl" attribute in slider parent tag**

```css
* {
    margin: 0;
    padding: 0;
}
.container {
    width: 60%;
    margin: 10px auto;
}
.main,
.nav {
    width: 100%;
}
.nav {
    display: flex;
    flex-direction: column;
}
```

```js
$(".main").slick({
    rtl: true,
    slidesToShow: 1,
    asNavFor: '.nav',
    focusOnSelect: true,
    slidesToScroll: 1,
    infinite: true
})
$(".nav").slick({
    rtl: true,
    slidesToShow: 3,
    asNavFor: '.main',
    focusOnSelect: true,
    slidesToScroll: 1,
    centerMode: true,
    infinite: true
})
```
