### ISSUE TITLE
Slick Vertical text cut off issue

### ISSUE THREAD

**Issue by yushanwebdev** [kenwheeler/slick#3953]
I got an text cut off issue when apply slick vertical. Can somebody provide me a solution.

here I reproduce my bug: 
https://yushanwebdev.github.io/problems/slick-vertical-text-cut-off/

Slick Version - 1.9.0

**Comment by agustinl** [comment]
Hi @yushanwebdev 

Your putting a `<span>` element, that have a `display :inline` property by default.

You can solve your issue adding the following CSS to your span element:

```css
span {
   min-height: 50px; /* Or whathever */
   display: block;
}
```
