### ISSUE TITLE
Feature Request - Space Between Option

### ISSUE THREAD

**Issue by emon4u** [kenwheeler/slick#4263]
Is there any option to add space between sliders or will you add one? 

Such as SweeperS, and OwlCarousel. Now we added space with a custom margin but the option to add space from the script would be nice.

**Comment by bracket-web** [comment]
Truly needed option for this slider it's very useful

**Comment by mosharofkhandokar** [comment]
It's very useful when we are working on responsive can you guys please add this options?

**Comment by layerdrops** [comment]
When most sliders give a gutter option in between sliders why are you guys not giving that? very useful feature you should add With this feature it will be a full packed slider.

**Comment by samratislamtushar** [comment]
Please add a option for  gutter option in between sliders that's very useful feature.

**Comment by pulaknondi** [comment]
The feature is most important please add this feature.

**Comment by rr-it** [comment]
As it is 2024 the browsers have evolved and here is a working solution for modern browsers!

Use `clip-path`: :tada:

```css
/* gutter width: 20px */

.slick-slider {
  margin-left: -10px;
  margin-right: -10px;
}
.slick-list {
  clip-path: inset(0 10px 0 10px);
  /* warning: do not set `margin` or `padding` to anything other than `0` here! */
  margin: 0;
  padding: 0;
}
.slick-slide {
  margin-left: 10px;
  margin-right: 10px;
  background-color: thistle;
}
```

Also see:
* https://caniuse.com/css-clip-path
* https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
