### ISSUE TITLE
Full width carousel impossible; horizontal scroll bar appears.

### ISSUE THREAD

**Issue by haopei** [kenwheeler/slick#587]
Hello great carousel tool,

I want to set a slideshow to use the browser's full width, but my attempt to edit the CSS to achieve this result seems to be fruitless. 

The problem can be best described right on http://kenwheeler.github.io/slick/. Let's open the Developer Tool on this page, and add the following code:

``` css

.slick-prev, .slick-next { width: 120px; !important } # Brings the next/prev buttons closer together
.blue h3{ margin: 0; background: black; !important } # Background made black so next/prev is visible
.content { padding: 0; width: auto; !important } # To make carousel span full width of browser
```

Looking at the first 'Single Item' demo, we would see that the carousel has now taken the full width of the page. This is the result that is desired. However, a horizontal scroll bar appears (please see attached screenshot).

![screen shot 2014-10-03 at 4 02 23 pm](https://cloud.githubusercontent.com/assets/445641/4511659/5146a6c2-4b37-11e4-9f5b-eba1af45c7af.png)

Any idea how to fix this? Thank you for any assistance!
