### ISSUE TITLE
Dragging class

### ISSUE THREAD

**Issue by woble** [kenwheeler/slick#967]
Hey, I noticed that in the original CSS there's a declaration for a class named 'dragging'. However in the script it doesn't come up at all.

I assume the following needs to be added to swipeStart / swipeEnd respectively: _.$list.addClass('dragging'); / _.$list.removeClass('dragging');

EDIT:
Also, by adding the following will prevent the dragging event from cancelling when hovering over the navigation buttons (not dots) while dragging.

````LESS
.slick-list {
    &.dragging {
        ~ button {
            pointer-events: none;
        }
    }
}
````
