### ISSUE TITLE
Extra 30px bottom margin problem

### ISSUE THREAD

**Issue by jsmad** [kenwheeler/slick#984]
The default CSS adds a mandatory 30px bottom margin, which causes all sorts of display problems if the html designer is not aware of it.

It would be better if this margin was optional, and only set when the "dots" are enabled.

```css
/* Dots */
.slick-slider
{
     margin-bottom: 30px; 
}
```
